services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ashareinsight-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ashareinsight}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ashareinsight_password}
      POSTGRES_DB: ${POSTGRES_DB:-ashareinsight_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ashareinsight} -d ${POSTGRES_DB:-ashareinsight_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ashareinsight-network
    command: >
      postgres
      -c shared_preload_libraries='vector'
      -c max_connections=${POSTGRES_MAX_CONNECTIONS:-200}
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-256MB}
      -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-1GB}
      -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-64MB}
      -c checkpoint_completion_target=${POSTGRES_CHECKPOINT_COMPLETION_TARGET:-0.7}
      -c wal_buffers=${POSTGRES_WAL_BUFFERS:-16MB}
      -c default_statistics_target=${POSTGRES_DEFAULT_STATISTICS_TARGET:-100}
      -c random_page_cost=${POSTGRES_RANDOM_PAGE_COST:-1.1}
      -c effective_io_concurrency=${POSTGRES_EFFECTIVE_IO_CONCURRENCY:-200}
      -c work_mem=${POSTGRES_WORK_MEM:-4MB}
      -c min_wal_size=${POSTGRES_MIN_WAL_SIZE:-1GB}
      -c max_wal_size=${POSTGRES_MAX_WAL_SIZE:-2GB}

  adminer:
    image: adminer:latest
    container_name: ashareinsight-adminer
    restart: unless-stopped
    ports:
      - "8124:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ashareinsight-network

  redis:
    image: redis:7-alpine
    container_name: ashareinsight-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ashareinsight-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ashareinsight-network:
    driver: bridge
    name: ashareinsight-network