version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ashareinsight-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ashareinsight}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ashareinsight_password}
      POSTGRES_DB: ${POSTGRES_DB:-ashareinsight_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ashareinsight} -d ${POSTGRES_DB:-ashareinsight_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ashareinsight-network
    command: >
      postgres
      -c shared_preload_libraries='vector'
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=2GB

  adminer:
    image: adminer:latest
    container_name: ashareinsight-adminer
    restart: unless-stopped
    ports:
      - "8124:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ashareinsight-network

  redis:
    image: redis:7-alpine
    container_name: ashareinsight-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ashareinsight-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ashareinsight-network:
    driver: bridge
    name: ashareinsight-network