# AShareInsight Development Configuration
# This file contains settings for the development environment

app:
  name: AShareInsight
  version: 0.1.0
  environment: development
  debug: true

database:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  name: ${POSTGRES_DB:ashareinsight_db}
  user: ${POSTGRES_USER:ashareinsight}
  password: ${POSTGRES_PASSWORD:ashareinsight_password}
  pool:
    min_size: 5
    max_size: 20
    timeout: 30
  
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:0}
  decode_responses: true
  
api:
  host: ${API_HOST:0.0.0.0}
  port: ${API_PORT:8000}
  workers: 1
  reload: true
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:8000"
    allow_credentials: true
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
    allow_headers:
      - Content-Type
      - Authorization

models:
  gemini:
    api_key: ${GEMINI_API_KEY}
    model: gemini-2.5-pro
    temperature: 0.1
    max_tokens: 4096
    
  embedding:
    service_url: ${QWEN_EMBEDDING_URL:http://localhost:8001/embeddings}
    model: Qwen3-Embedding-4B
    dimension: 2560
    batch_size: 32
    
  reranker:
    service_url: ${QWEN_RERANKER_URL:http://localhost:8002/rerank}
    model: Qwen-Reranker
    top_k: 10

vector_store:
  similarity_threshold: 0.7
  max_results: 20
  index:
    distance_metric: cosine  # Options: l2, cosine, ip (inner product)
    m: 16
    ef_construction: 64
    ef_search: 40

logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  handlers:
    console:
      enabled: true
      level: DEBUG
    file:
      enabled: true
      level: INFO
      path: logs/ashareinsight.log
      rotation:
        max_bytes: 10485760  # 10MB
        backup_count: 5

monitoring:
  telemetry:
    enabled: ${ENABLE_TELEMETRY:true}
    endpoint: ${OTLP_ENDPOINT:http://localhost:4317}
    service_name: ashareinsight-api
    
  metrics:
    enabled: true
    port: 9090
    
  healthcheck:
    enabled: true
    path: /health
    interval: 30

processing:
  batch_size: 100
  max_workers: 4
  timeout: 300
  retry:
    max_attempts: 3
    backoff_factor: 2
    
paths:
  documents: data/documents
  outputs: data/outputs
  dead_letter: data/dead_letter_queue
  temp: tmp/